update message

diff --git a/workflows/maven_jar_execute.yml b/workflows/maven_jar_execute.yml
--- a/workflows/maven_jar_execute.yml
+++ b/workflows/maven_jar_execute.yml
@@ -23,8 +23,25 @@ jobs:
         with:
           java-version: '17'
           distribution: 'temurin'
-          cache: maven
+      - name: Check if Maven is installed
+        run: |
+            if ! command -v mvn &> /dev/null; then
+              echo "Maven not found, installing..."
+              echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S yum install -y maven
+            else
+              echo "Maven is already installed"
+            fi
       - name: Build with Maven
         run: mvn -B package --file pom.xml
+      - name: Run sudo lsof command
+        run: |
+          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lsof -i -P -n | grep LISTEN
+      - name: Check for Running Containers Exposing Port 80
+        id: check-containers
+        run: |
+            if echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lsof -t -i:80 > /dev/null; then
+              echo "There are running port 80."
+              echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S kill -9 $(echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lsof -t -i:80)
+            fi
       - name: JVM and execute in Background
-        run: java -jar target/MSB-0.0.1-SNAPSHOT.war &
+        run: echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S java -jar target/MSB-0.0.1-SNAPSHOT.war &
