update message

diff --git a/workflows/maven_jar_execute.yml b/workflows/maven_jar_execute.yml
--- a/workflows/maven_jar_execute.yml
+++ b/workflows/maven_jar_execute.yml
@@ -13,35 +13,80 @@ on:
     branches: [ "main" ]
 
 jobs:
-  build:
-
+  check-java-maven:
+    name: Verify Java Maven Dependency
     runs-on: self-hosted
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v3
       - name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
           java-version: '17'
           distribution: 'temurin'
-      - name: Check if Maven is installed
+      - name: Check if Verify is not installed; if it isn't, then proceed with its installation.
         run: |
-            if ! command -v mvn &> /dev/null; then
-              echo "Maven not found, installing..."
-              echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S yum install -y maven
-            else
-              echo "Maven is already installed"
+          if ! command -v mvn &> /dev/null; then
+            echo "Maven not found, installing..."
+            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S yum install -y maven
+          else
+            echo "Maven is already installed"
+          fi
+  check-port:
+    name: Verify rocesses on Port 80 if Present
+    runs-on: self-hosted
+    needs: check-java-maven
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: List of Ports Currently in the LISTEN State
+        run: echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lsof -i -P -n | grep LISTEN
+      - name: Adentify the Process on Port 80
+        id: check-port
+        run: |
+          if echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lsof -t -i:80 > /dev/null; then
+            echo "An existing process is currently active on port 80. It's time to terminate this process."
+            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S kill -9 $(echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lsof -t -i:80)
+          fi
+  check-docker:
+    name: Verify Docker Installation and Terminate Processes on Port 80 if Present
+    runs-on: self-hosted
+    needs: check-port
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Check if Docker is not installed; if it isn't, then proceed with its installation and startup.
+        id: check-docker
+        run: |
+          if command -v docker &> /dev/null; then
+            echo "Docker is installed"
+            echo "docker_exist=true" >> $GITHUB_ENV
+          else
+            echo "Docker is not installed"
+            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S yum update -y
+            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S yum install -y docker
+            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl start docker
+            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl enable docker
+            echo "docker_exist=false" >> $GITHUB_ENV
+          fi
+      - name: Identify the containers with active processes on Port 80, and subsequently, halt them.
+        env:
+          CONTAINERS_EXIST: ${{ steps.check-docker.outputs.docker_exist }}
+        run: |
+          if [ "$CONTAINERS_EXIST" = "true" ]; then
+            echo "Running commands for existing containers."
+            if docker ps -q --filter "expose=80/tcp" --filter "status=running" > /dev/null; then
+              docker stop $(docker ps -q --filter "expose=80/tcp" --filter "status=running") 
             fi
+          fi
+  build:
+    name: Build Java Maven Dependency  Project
+    runs-on: self-hosted
+    needs: check-docker
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
       - name: Build with Maven
         run: mvn -B package --file pom.xml
-      - name: Run sudo lsof command
-        run: |
-          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lsof -i -P -n | grep LISTEN
-      - name: Check for Running Containers Exposing Port 80
-        id: check-containers
-        run: |
-            if echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lsof -t -i:80 > /dev/null; then
-              echo "There are running port 80."
-              echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S kill -9 $(echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lsof -t -i:80)
-            fi
-      - name: JVM and execute in Background
+      - name: Execute the project in the background using the JVM with the command 'java -jar target/..SNAPSHOT.war'
         run: echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S java -jar target/MSB-0.0.1-SNAPSHOT.war &
