update message

diff --git a/.github/workflows/check-dependency.yml b/.github/workflows/check-dependency.yml
--- a/.github/workflows/check-dependency.yml
+++ b/.github/workflows/check-dependency.yml
@@ -11,14 +11,14 @@ jobs:
     steps:
       - name: "Checkout code"
         uses: actions/checkout@v3
-      - name: "Ensure that Docker is installed"
-        id: check-docker
+      - name: "Set up JDK 17"
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+      - name: "Ensure that Maven is installed"
         run: |
-          if ! command -v docker &> /dev/null; then
-            echo "Docker is not installed"
-            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S yum update -y
-            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S yum install -y docker
-            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl start docker
-            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl enable docker
-            echo "docker_exist=false" >> $GITHUB_ENV
+          if ! command -v mvn &> /dev/null; then
+            echo "Maven not found, installing..."
+            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S yum install -y maven
           fi
