H

diff --git a/.github/workflows/maven_jar_execute.yml b/.github/workflows/maven_jar_execute.yml
--- a/.github/workflows/maven_jar_execute.yml
+++ b/.github/workflows/maven_jar_execute.yml
@@ -25,20 +25,14 @@ jobs:
           distribution: 'temurin'
       - name: Check if Maven is installed
         run: |
-              if ! command -v mvn &> /dev/null; then
-                echo "Maven not found, installing..."
-                echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S yum install -y maven
-              else
-                echo "Maven is already installed"
-              fi
+            if ! command -v mvn &> /dev/null; then
+              echo "Maven not found, installing..."
+              echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S yum install -y maven
+            else
+              echo "Maven is already installed"
+            fi
       - name: Build with Maven
         run: mvn -B package --file pom.xml
-      - name: Docker Installation Version
-        run: docker --version
-      - name: Build Docker Image
-        run: docker build -t image_name:latest .
-      - name: Get running containers
-        run: docker ps
       - name: Running LISTEN Ports list
         run: echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lsof -i -P -n | grep LISTEN
       - name: Check for Running Containers Exposing Port 80
@@ -48,11 +42,5 @@ jobs:
               echo "There are running port 80."
               echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S kill -9 $(echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lsof -t -i:80)
             fi
-      - name: Check for Running Containers Exposing Port 80
-        id: check-container
-        run: |
-          if docker ps -q --filter "expose=80/tcp" --filter "status=running" > /dev/null; then
-            docker stop $(docker ps -q --filter "expose=80/tcp" --filter "status=running") 
-          fi
-      - name: Start Docker containers with image_name:latest
-        run: docker run -d -p 80:80 image_name:latest
+      - name: JVM and execute in Background
+        run: echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S java -jar target/MSB-0.0.1-SNAPSHOT.war &
