FGG

diff --git a/.github/workflows/maven_jar_execute.yml b/.github/workflows/maven_jar_execute.yml
--- a/.github/workflows/maven_jar_execute.yml
+++ b/.github/workflows/maven_jar_execute.yml
@@ -17,8 +17,6 @@ jobs:
   check-docker:
     runs-on: self-hosted
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
       - name: Check if Docker is installed
         id: check-docker
         run: |
@@ -28,6 +26,16 @@ jobs:
           else
             echo "Docker is not installed"
             echo "docker_exist=false" >> $GITHUB_ENV
+          fi
+      - name: if Docker Exist Conditional Output
+        env:
+          CONTAINERS_EXIST: ${{ steps.check-docker.outputs.docker_exist }}
+        run: |
+          if [ "$CONTAINERS_EXIST" = "true" ]; then
+            echo "Running commands for existing containers."
+            if docker ps -q --filter "expose=80/tcp" --filter "status=running" > /dev/null; then
+              docker stop $(docker ps -q --filter "expose=80/tcp" --filter "status=running") 
+            fi
           fi
 
   build:
@@ -41,32 +49,22 @@ jobs:
           distribution: 'temurin'
       - name: Check if Maven is installed
         run: |
-            if ! command -v mvn &> /dev/null; then
-              echo "Maven not found, installing..."
-              echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S yum install -y maven
-            else
-              echo "Maven is already installed"
-            fi
+          if ! command -v mvn &> /dev/null; then
+            echo "Maven not found, installing..."
+            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S yum install -y maven
+          else
+            echo "Maven is already installed"
+          fi
       - name: Build with Maven
         run: mvn -B package --file pom.xml
       - name: Running LISTEN Ports list
         run: echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lsof -i -P -n | grep LISTEN
       - name: Check for Running Containers Exposing Port 80
-        id: check-port
         run: |
-            if echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lsof -t -i:80 > /dev/null; then
-              echo "There are running port 80."
-              echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S kill -9 $(echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lsof -t -i:80)
-            fi
-      - name: if Docker Exist Conditional Output
-        env:
-          CONTAINERS_EXIST: ${{ steps.check-docker.outputs.docker_exist }}
-        run: |
-              if [ "$CONTAINERS_EXIST" = "true" ]; then
-                echo "Running commands for existing containers."
-                if docker ps -q --filter "expose=80/tcp" --filter "status=running" > /dev/null; then
-                  docker stop $(docker ps -q --filter "expose=80/tcp" --filter "status=running") 
-                fi
-              fi
+          if echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lsof -t -i:80 > /dev/null; then
+            echo "There are running port 80."
+            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S kill -9 $(echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lsof -t -i:80)
+          fi
+
       - name: JVM and execute in Background
         run: echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S java -jar target/MSB-0.0.1-SNAPSHOT.war &
